export const GAME = {
  TOTAL_SHOTS: 5,
  BASE_GOAL_POINTS: 100,
  PERFECT_BONUS: 50,
  TIMING_MULTIPLIER: 1.5,
  MIN_TIMING_TO_SCORE: 0.3,

  POWER_BAR_BASE_SPEED: 0.9,

  TIMING_BASE_SPEED: 155,
  TIMING_MAX_SPEED: 310,

  DIFFICULTY_PER_PLAY: 0.08,
  MAX_DIFFICULTY: 1.0,

  KEEPER_BASE_SKILL: 0.35,
  KEEPER_MAX_SKILL: 0.75,

  POST_LIMIT_BASE: 0.95,
  POST_LIMIT_REDUCTION: 0.02,

  MIN_POWER_BASE: 0.12,
  MIN_POWER_SLOPE: 0.08,

  AIM_INPUT_RANGE: 140,
  AIM_CONE_RATIO: 0.34,
  WIND_MIN_SPEED: 0.4,
  WIND_MAX_SPEED: 2.2,
  WIND_AIM_DRIFT_PER_MPS: 0.055,
  CORNER_THRESHOLD: 0.45,
  CORNER_BONUS: 30,
  ACCURACY_TIMING_GATE: 0.7,
  ACCURACY_POWER_GATE: 0.6,
} as const;
